name: CI

on:
  push:
    branches:
      - main
      - support/*
  pull_request:
  workflow_dispatch:

jobs:
  php:
    name: PHP
    uses: Icinga/github-actions/.github/workflows/php.yml@main
    with:
      setup-commands: sudo locale-gen de_DE.UTF-8 en_US.UTF-8 it_IT.UTF-8
